name: Clojure CI

on: [push]

jobs:
  build:
    name: Clojure Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.507'
      - uses: prewk/s3-cp-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE: 's3://my-brother-is-in-politics-i-am-sure-you-understand/dev-local-1.0.243.jar'
          DEST: '.'
      - name: Install dev-local
        run: mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=dev-local-1.0.243.jar
      - name: Create dev-local.edn
        run: |
          mkdir $HOME/.datomic
          cd $HOME/.datomic
          echo '{:storage-dir "/home/runner"}' > dev-local.edn
      - name: Run clj tests
        run: bin/kaocha clj-unit
